// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narnndzvmpbqbuyoulvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcm5uZHp2bXBicWJ1eW91bHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDMyODIsImV4cCI6MjA2Nzg3OTI4Mn0.2BeFws0XDdCdp9yaPbbF3heDc7nVeUAzrpI5kHhpIIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});